[tools]
go = "1.26.4"
"go:github.com/d2lang/d2" = "0.9.0"
"go:github.com/go-delve/delve/cmd/dlv" = "1.27.1"
"go:golang.org/x/tools/gopls" = "0.23.0"
pipx ='1.8.0'
"pipx:supervisor" = "4.3.0"

[env]
TM_ROOT = "{{config_root}}"
